CREATE TABLE sistema.claves_api (
 id BIGSERIAL PRIMARY KEY,
 propietario VARCHAR(100) NOT NULL REFERENCES public.users(username),
 conexion_id BIGINT NOT NULL REFERENCES sistema.conexiones_bases_datos(id) ON DELETE CASCADE,
 nombre VARCHAR(100) NOT NULL,
 huella CHAR(64) NOT NULL UNIQUE,
 prefijo VARCHAR(16) NOT NULL,
 permite_escritura BOOLEAN NOT NULL DEFAULT FALSE,
 activa BOOLEAN NOT NULL DEFAULT TRUE,
 creada TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 vence TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '30 days'
);
